In [ ]:
!pip install beautifulsoup4

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.8/dist-packages (4.6.3)

In [ ]:
import requests
# Create an URL object
url = 'https://stats.espncricinfo.com/ci/engine/records/team/match_results.html?id=14450;type=tournament'
# Create object page
page = requests.get(url)
print(page)
# If the output is <Response [200]> that means the server allows us to collect data from their website.

<Response [200]>

In [ ]:
from bs4 import BeautifulSoup
# parser-lxml = Change html to Python friendly format
# Obtain page's information
soup = BeautifulSoup(page.text, 'lxml')

In [ ]:
all_links = []
match_links = []

for link in soup.select('a.data-link'):
  all_links.append('https://stats.espncricinfo.com' + link.get('href'))

for link in all_links:
  if link.find('match') >= 0:
    match_links.append(link)

print(all_links)
print(match_links)

['https://stats.espncricinfo.com/ci/content/team/28.html', 'https://stats.espncricinfo.com/ci/content/team/8.html', 'https://stats.espncricinfo.com/ci/content/team/28.html', 'https://stats.espncricinfo.com/ci/content/ground/56402.html', 'https://stats.espncricinfo.com/ci/engine/match/1298135.html', 'https://stats.espncricinfo.com/ci/content/team/15.html', 'https://stats.espncricinfo.com/ci/content/team/27.html', 'https://stats.espncricinfo.com/ci/content/team/15.html', 'https://stats.espncricinfo.com/ci/content/ground/56402.html', 'https://stats.espncricinfo.com/ci/engine/match/1298136.html', 'https://stats.espncricinfo.com/ci/content/team/30.html', 'https://stats.espncricinfo.com/ci/content/team/4.html', 'https://stats.espncricinfo.com/ci/content/team/30.html', 'https://stats.espncricinfo.com/ci/content/ground/56407.html', 'https://stats.espncricinfo.com/ci/engine/match/1298137.html', 'https://stats.espncricinfo.com/ci/content/team/29.html', 'https://stats.espncricinfo.com/ci/content/team/9.html', 'https://stats.espncricinfo.com/ci/content/team/9.html', 'https://stats.espncricinfo.com/ci/content/ground/56407.html', 'https://stats.espncricinfo.com/ci/engine/match/1298138.html', 'https://stats.espncricinfo.com/ci/content/team/28.html', 'https://stats.espncricinfo.com/ci/content/team/15.html', 'https://stats.espncricinfo.com/ci/content/team/15.html', 'https://stats.espncricinfo.com/ci/content/ground/56402.html', 'https://stats.espncricinfo.com/ci/engine/match/1298139.html', 'https://stats.espncricinfo.com/ci/content/team/8.html', 'https://stats.espncricinfo.com/ci/content/team/27.html', 'https://stats.espncricinfo.com/ci/content/team/8.html', 'https://stats.espncricinfo.com/ci/content/ground/56402.html', 'https://stats.espncricinfo.com/ci/engine/match/1298140.html', 'https://stats.espncricinfo.com/ci/content/team/29.html', 'https://stats.espncricinfo.com/ci/content/team/30.html', 'https://stats.espncricinfo.com/ci/content/team/29.html', 'https://stats.espncricinfo.com/ci/content/ground/56407.html', 'https://stats.espncricinfo.com/ci/engine/match/1298141.html', 'https://stats.espncricinfo.com/ci/content/team/4.html', 'https://stats.espncricinfo.com/ci/content/team/9.html', 'https://stats.espncricinfo.com/ci/content/team/4.html', 'https://stats.espncricinfo.com/ci/content/ground/56407.html', 'https://stats.espncricinfo.com/ci/engine/match/1298142.html', 'https://stats.espncricinfo.com/ci/content/team/15.html', 'https://stats.espncricinfo.com/ci/content/team/8.html', 'https://stats.espncricinfo.com/ci/content/team/8.html', 'https://stats.espncricinfo.com/ci/content/ground/56402.html', 'https://stats.espncricinfo.com/ci/engine/match/1298143.html', 'https://stats.espncricinfo.com/ci/content/team/28.html', 'https://stats.espncricinfo.com/ci/content/team/27.html', 'https://stats.espncricinfo.com/ci/content/team/27.html', 'https://stats.espncricinfo.com/ci/content/ground/56402.html', 'https://stats.espncricinfo.com/ci/engine/match/1298144.html', 'https://stats.espncricinfo.com/ci/content/team/29.html', 'https://stats.espncricinfo.com/ci/content/team/4.html', 'https://stats.espncricinfo.com/ci/content/team/29.html', 'https://stats.espncricinfo.com/ci/content/ground/56407.html', 'https://stats.espncricinfo.com/ci/engine/match/1298145.html', 'https://stats.espncricinfo.com/ci/content/team/30.html', 'https://stats.espncricinfo.com/ci/content/team/9.html', 'https://stats.espncricinfo.com/ci/content/team/9.html', 'https://stats.espncricinfo.com/ci/content/ground/56407.html', 'https://stats.espncricinfo.com/ci/engine/match/1298146.html', 'https://stats.espncricinfo.com/ci/content/team/2.html', 'https://stats.espncricinfo.com/ci/content/team/5.html', 'https://stats.espncricinfo.com/ci/content/team/5.html', 'https://stats.espncricinfo.com/ci/content/ground/56544.html', 'https://stats.espncricinfo.com/ci/engine/match/1298147.html', 'https://stats.espncricinfo.com/ci/content/team/40.html', 'https://stats.espncricinfo.com/ci/content/team/1.html', 'https://stats.espncricinfo.com/ci/content/team/1.html', 'https://stats.espncricinfo.com/ci/content/ground/1126475.html', 'https://stats.espncricinfo.com/ci/engine/match/1298148.html', 'https://stats.espncricinfo.com/ci/content/team/29.html', 'https://stats.espncricinfo.com/ci/content/team/8.html', 'https://stats.espncricinfo.com/ci/content/team/8.html', 'https://stats.espncricinfo.com/ci/content/ground/56407.html', 'https://stats.espncricinfo.com/ci/engine/match/1298149.html', 'https://stats.espncricinfo.com/ci/content/team/6.html', 'https://stats.espncricinfo.com/ci/content/team/7.html', 'https://stats.espncricinfo.com/ci/content/team/6.html', 'https://stats.espncricinfo.com/ci/content/ground/56441.html', 'https://stats.espncricinfo.com/ci/engine/match/1298150.html', 'https://stats.espncricinfo.com/ci/content/team/25.html', 'https://stats.espncricinfo.com/ci/content/team/15.html', 'https://stats.espncricinfo.com/ci/content/team/25.html', 'https://stats.espncricinfo.com/ci/content/ground/56407.html', 'https://stats.espncricinfo.com/ci/engine/match/1298151.html', 'https://stats.espncricinfo.com/ci/content/team/3.html', 'https://stats.espncricinfo.com/ci/content/team/9.html', 'https://stats.espncricinfo.com/ci/content/ground/56407.html', 'https://stats.espncricinfo.com/ci/engine/match/1298152.html', 'https://stats.espncricinfo.com/ci/content/team/2.html', 'https://stats.espncricinfo.com/ci/content/team/8.html', 'https://stats.espncricinfo.com/ci/content/team/2.html', 'https://stats.espncricinfo.com/ci/content/ground/1126475.html', 'https://stats.espncricinfo.com/ci/engine/match/1298153.html', 'https://stats.espncricinfo.com/ci/content/team/1.html', 'https://stats.espncricinfo.com/ci/content/team/29.html', 'https://stats.espncricinfo.com/ci/content/team/29.html', 'https://stats.espncricinfo.com/ci/content/ground/56441.html', 'https://stats.espncricinfo.com/ci/engine/match/1298154.html', 'https://stats.espncricinfo.com/ci/content/team/40.html', 'https://stats.espncricinfo.com/ci/content/team/5.html', 'https://stats.espncricinfo.com/ci/content/ground/56441.html', 'https://stats.espncricinfo.com/ci/engine/match/1298155.html', 'https://stats.espncricinfo.com/ci/content/team/25.html', 'https://stats.espncricinfo.com/ci/content/team/3.html', 'https://stats.espncricinfo.com/ci/content/team/3.html', 'https://stats.espncricinfo.com/ci/content/ground/56544.html', 'https://stats.espncricinfo.com/ci/engine/match/1298156.html', 'https://stats.espncricinfo.com/ci/content/team/6.html', 'https://stats.espncricinfo.com/ci/content/team/15.html', 'https://stats.espncricinfo.com/ci/content/team/6.html', 'https://stats.espncricinfo.com/ci/content/ground/56544.html', 'https://stats.espncricinfo.com/ci/engine/match/1298157.html', 'https://stats.espncricinfo.com/ci/content/team/7.html', 'https://stats.espncricinfo.com/ci/content/team/9.html', 'https://stats.espncricinfo.com/ci/content/team/9.html', 'https://stats.espncricinfo.com/ci/content/ground/1126475.html', 'https://stats.espncricinfo.com/ci/engine/match/1298158.html', 'https://stats.espncricinfo.com/ci/content/team/40.html', 'https://stats.espncricinfo.com/ci/content/team/29.html', 'https://stats.espncricinfo.com/ci/content/ground/56441.html', 'https://stats.espncricinfo.com/ci/engine/match/1298159.html', 'https://stats.espncricinfo.com/ci/content/team/2.html', 'https://stats.espncricinfo.com/ci/content/team/1.html', 'https://stats.espncricinfo.com/ci/content/ground/56441.html', 'https://stats.espncricinfo.com/ci/engine/match/1298160.html', 'https://stats.espncricinfo.com/ci/content/team/5.html', 'https://stats.espncricinfo.com/ci/content/team/8.html', 'https://stats.espncricinfo.com/ci/content/team/5.html', 'https://stats.espncricinfo.com/ci/content/ground/56544.html', 'https://stats.espncricinfo.com/ci/engine/match/1298161.html', 'https://stats.espncricinfo.com/ci/content/team/25.html', 'https://stats.espncricinfo.com/ci/content/team/9.html', 'https://stats.espncricinfo.com/ci/content/team/25.html', 'https://stats.espncricinfo.com/ci/content/ground/56336.html', 'https://stats.espncricinfo.com/ci/engine/match/1298162.html', 'https://stats.espncricinfo.com/ci/content/team/15.html', 'https://stats.espncricinfo.com/ci/content/team/7.html', 'https://stats.espncricinfo.com/ci/content/team/7.html', 'https://stats.espncricinfo.com/ci/content/ground/1126475.html', 'https://stats.espncricinfo.com/ci/engine/match/1298163.html', 'https://stats.espncricinfo.com/ci/content/team/6.html', 'https://stats.espncricinfo.com/ci/content/team/3.html', 'https://stats.espncricinfo.com/ci/content/team/3.html', 'https://stats.espncricinfo.com/ci/content/ground/1126475.html', 'https://stats.espncricinfo.com/ci/engine/match/1298164.html', 'https://stats.espncricinfo.com/ci/content/team/2.html', 'https://stats.espncricinfo.com/ci/content/team/29.html', 'https://stats.espncricinfo.com/ci/content/team/2.html', 'https://stats.espncricinfo.com/ci/content/ground/56336.html', 'https://stats.espncricinfo.com/ci/engine/match/1298165.html', 'https://stats.espncricinfo.com/ci/content/team/40.html', 'https://stats.espncricinfo.com/ci/content/team/8.html', 'https://stats.espncricinfo.com/ci/content/team/8.html', 'https://stats.espncricinfo.com/ci/content/ground/56336.html', 'https://stats.espncricinfo.com/ci/engine/match/1298166.html', 'https://stats.espncricinfo.com/ci/content/team/1.html', 'https://stats.espncricinfo.com/ci/content/team/5.html', 'https://stats.espncricinfo.com/ci/content/team/1.html', 'https://stats.espncricinfo.com/ci/content/ground/56336.html', 'https://stats.espncricinfo.com/ci/engine/match/1298167.html', 'https://stats.espncricinfo.com/ci/content/team/15.html', 'https://stats.espncricinfo.com/ci/content/team/9.html', 'https://stats.espncricinfo.com/ci/content/team/15.html', 'https://stats.espncricinfo.com/ci/content/ground/56293.html', 'https://stats.espncricinfo.com/ci/engine/match/1298168.html', 'https://stats.espncricinfo.com/ci/content/team/25.html', 'https://stats.espncricinfo.com/ci/content/team/6.html', 'https://stats.espncricinfo.com/ci/content/team/6.html', 'https://stats.espncricinfo.com/ci/content/ground/56293.html', 'https://stats.espncricinfo.com/ci/engine/match/1298169.html', 'https://stats.espncricinfo.com/ci/content/team/7.html', 'https://stats.espncricinfo.com/ci/content/team/3.html', 'https://stats.espncricinfo.com/ci/content/team/7.html', 'https://stats.espncricinfo.com/ci/content/ground/56544.html', 'https://stats.espncricinfo.com/ci/engine/match/1298170.html', 'https://stats.espncricinfo.com/ci/content/team/29.html', 'https://stats.espncricinfo.com/ci/content/team/5.html', 'https://stats.espncricinfo.com/ci/content/team/5.html', 'https://stats.espncricinfo.com/ci/content/ground/56293.html', 'https://stats.espncricinfo.com/ci/engine/match/1298171.html', 'https://stats.espncricinfo.com/ci/content/team/2.html', 'https://stats.espncricinfo.com/ci/content/team/40.html', 'https://stats.espncricinfo.com/ci/content/team/2.html', 'https://stats.espncricinfo.com/ci/content/ground/56293.html', 'https://stats.espncricinfo.com/ci/engine/match/1298172.html', 'https://stats.espncricinfo.com/ci/content/team/1.html', 'https://stats.espncricinfo.com/ci/content/team/8.html', 'https://stats.espncricinfo.com/ci/content/team/1.html', 'https://stats.espncricinfo.com/ci/content/ground/56544.html', 'https://stats.espncricinfo.com/ci/engine/match/1298173.html', 'https://stats.espncricinfo.com/ci/content/team/15.html', 'https://stats.espncricinfo.com/ci/content/team/3.html', 'https://stats.espncricinfo.com/ci/content/team/15.html', 'https://stats.espncricinfo.com/ci/content/ground/56293.html', 'https://stats.espncricinfo.com/ci/engine/match/1298174.html', 'https://stats.espncricinfo.com/ci/content/team/25.html', 'https://stats.espncricinfo.com/ci/content/team/7.html', 'https://stats.espncricinfo.com/ci/content/team/7.html', 'https://stats.espncricinfo.com/ci/content/ground/56293.html', 'https://stats.espncricinfo.com/ci/engine/match/1298175.html', 'https://stats.espncricinfo.com/ci/content/team/6.html', 'https://stats.espncricinfo.com/ci/content/team/9.html', 'https://stats.espncricinfo.com/ci/content/team/6.html', 'https://stats.espncricinfo.com/ci/content/ground/56441.html', 'https://stats.espncricinfo.com/ci/engine/match/1298176.html', 'https://stats.espncricinfo.com/ci/content/team/5.html', 'https://stats.espncricinfo.com/ci/content/team/7.html', 'https://stats.espncricinfo.com/ci/content/team/7.html', 'https://stats.espncricinfo.com/ci/content/ground/56544.html', 'https://stats.espncricinfo.com/ci/engine/match/1298177.html', 'https://stats.espncricinfo.com/ci/content/team/1.html', 'https://stats.espncricinfo.com/ci/content/team/6.html', 'https://stats.espncricinfo.com/ci/content/team/1.html', 'https://stats.espncricinfo.com/ci/content/ground/56293.html', 'https://stats.espncricinfo.com/ci/engine/match/1298178.html', 'https://stats.espncricinfo.com/ci/content/team/1.html', 'https://stats.espncricinfo.com/ci/content/team/7.html', 'https://stats.espncricinfo.com/ci/content/team/1.html', 'https://stats.espncricinfo.com/ci/content/ground/56441.html', 'https://stats.espncricinfo.com/ci/engine/match/1298179.html']
['https://stats.espncricinfo.com/ci/engine/match/1298135.html', 'https://stats.espncricinfo.com/ci/engine/match/1298136.html', 'https://stats.espncricinfo.com/ci/engine/match/1298137.html', 'https://stats.espncricinfo.com/ci/engine/match/1298138.html', 'https://stats.espncricinfo.com/ci/engine/match/1298139.html', 'https://stats.espncricinfo.com/ci/engine/match/1298140.html', 'https://stats.espncricinfo.com/ci/engine/match/1298141.html', 'https://stats.espncricinfo.com/ci/engine/match/1298142.html', 'https://stats.espncricinfo.com/ci/engine/match/1298143.html', 'https://stats.espncricinfo.com/ci/engine/match/1298144.html', 'https://stats.espncricinfo.com/ci/engine/match/1298145.html', 'https://stats.espncricinfo.com/ci/engine/match/1298146.html', 'https://stats.espncricinfo.com/ci/engine/match/1298147.html', 'https://stats.espncricinfo.com/ci/engine/match/1298148.html', 'https://stats.espncricinfo.com/ci/engine/match/1298149.html', 'https://stats.espncricinfo.com/ci/engine/match/1298150.html', 'https://stats.espncricinfo.com/ci/engine/match/1298151.html', 'https://stats.espncricinfo.com/ci/engine/match/1298152.html', 'https://stats.espncricinfo.com/ci/engine/match/1298153.html', 'https://stats.espncricinfo.com/ci/engine/match/1298154.html', 'https://stats.espncricinfo.com/ci/engine/match/1298155.html', 'https://stats.espncricinfo.com/ci/engine/match/1298156.html', 'https://stats.espncricinfo.com/ci/engine/match/1298157.html', 'https://stats.espncricinfo.com/ci/engine/match/1298158.html', 'https://stats.espncricinfo.com/ci/engine/match/1298159.html', 'https://stats.espncricinfo.com/ci/engine/match/1298160.html', 'https://stats.espncricinfo.com/ci/engine/match/1298161.html', 'https://stats.espncricinfo.com/ci/engine/match/1298162.html', 'https://stats.espncricinfo.com/ci/engine/match/1298163.html', 'https://stats.espncricinfo.com/ci/engine/match/1298164.html', 'https://stats.espncricinfo.com/ci/engine/match/1298165.html', 'https://stats.espncricinfo.com/ci/engine/match/1298166.html', 'https://stats.espncricinfo.com/ci/engine/match/1298167.html', 'https://stats.espncricinfo.com/ci/engine/match/1298168.html', 'https://stats.espncricinfo.com/ci/engine/match/1298169.html', 'https://stats.espncricinfo.com/ci/engine/match/1298170.html', 'https://stats.espncricinfo.com/ci/engine/match/1298171.html', 'https://stats.espncricinfo.com/ci/engine/match/1298172.html', 'https://stats.espncricinfo.com/ci/engine/match/1298173.html', 'https://stats.espncricinfo.com/ci/engine/match/1298174.html', 'https://stats.espncricinfo.com/ci/engine/match/1298175.html', 'https://stats.espncricinfo.com/ci/engine/match/1298176.html', 'https://stats.espncricinfo.com/ci/engine/match/1298177.html', 'https://stats.espncricinfo.com/ci/engine/match/1298178.html', 'https://stats.espncricinfo.com/ci/engine/match/1298179.html']

In [ ]:
# For a single match
# match_url = match_links[0]
# match_page = requests.get(match_url)
# soup = BeautifulSoup(match_page.text, 'html.parser')

# teams = soup.find_all("span", class_="ds-text-title-xs ds-font-bold ds-capitalize")
# team1 = teams[0].text
# team2 = teams[1].text
# match = team1 + ' Vs ' + team2
# print(match)

In [ ]:
# Single Match
match_url = 'https://www.espncricinfo.com/series/icc-men-s-t20-world-cup-2022-23-1298134/namibia-vs-united-arab-emirates-10th-match-first-round-group-a-1298144/full-scorecard'
match_page = requests.get(match_url)
soup = BeautifulSoup(match_page.text, 'html.parser')

import pandas as pd
headers = ["match", "bowlingTeam", "bowlerName", "overs", "maiden", "runs", "wickets", "economy", "0s", "4s", "6s", "wides", "noBalls"]
bowling_data = pd.DataFrame(columns = headers)

if soup.find_all("span", class_="ds-text-title-xs ds-font-bold ds-capitalize"):
  teams = soup.find_all("span", class_="ds-text-title-xs ds-font-bold ds-capitalize")
  team1 = teams[0].text
  team2 = teams[1].text
  match = team1 + ' Vs ' + team2

tables = soup.find_all("table", {"class":"ds-table"}) 
print(len(tables))
team1_bowling = tables[1]
team2_bowling = tables[3]

# print(team1_bowling)
# print(team2_bowling)
print(len(team2_bowling))

for j in team1_bowling.find_all('tr')[1:]:
  if len(j.find_all('td')) >= 11:
    row_data = j.find_all('td')
  else:
    continue
  
  full_row = [match, team2]
  rest_row = [i.text for i in row_data]
  full_row.extend(rest_row)

  print(full_row)

  length = len(bowling_data)
  bowling_data.loc[length] = full_row

# bowling_data

for j in team2_bowling.find_all('tr')[1:]:
  if len(j.find_all('td')) >= 11:
    row_data = j.find_all('td')
  else:
    continue
  
  full_row = [match, team1]
  rest_row = [i.text for i in row_data]
  full_row.extend(rest_row)

  print(full_row)

  length = len(bowling_data)
  bowling_data.loc[length] = full_row

bowling_data

12
2
['United Arab Emirates Vs Namibia', 'Namibia', 'Ruben Trumpelmann', '4', '0', '22', '0', '5.50', '10', '0', '0', '3', '0']
['United Arab Emirates Vs Namibia', 'Namibia', 'David Wiese', '4', '0', '27', '1', '6.75', '12', '2', '1', '1', '0']
['United Arab Emirates Vs Namibia', 'Namibia', 'Bernard Scholtz', '4', '0', '22', '1', '5.50', '11', '1', '1', '0', '0']
['United Arab Emirates Vs Namibia', 'Namibia', 'JJ Smit', '4', '0', '39', '0', '9.75', '11', '2', '3', '0', '0']
['United Arab Emirates Vs Namibia', 'Namibia', 'Jan Frylinck', '3', '0', '30', '0', '10.00', '3', '2', '1', '1', '0']
['United Arab Emirates Vs Namibia', 'Namibia', 'Ben Shikongo', '1', '0', '8', '1', '8.00', '1', '1', '0', '0', '0']
['United Arab Emirates Vs Namibia', 'United Arab Emirates', 'Basil Hameed', '3', '0', '17', '2', '5.66', '10', '2', '0', '0', '0']

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls
0,United Arab Emirates Vs Namibia,Namibia,Ruben Trumpelmann,4,0,22,0,5.50,10,0,0,3,0
1,United Arab Emirates Vs Namibia,Namibia,David Wiese,4,0,27,1,6.75,12,2,1,1,0
2,United Arab Emirates Vs Namibia,Namibia,Bernard Scholtz,4,0,22,1,5.50,11,1,1,0,0
3,United Arab Emirates Vs Namibia,Namibia,JJ Smit,4,0,39,0,9.75,11,2,3,0,0
4,United Arab Emirates Vs Namibia,Namibia,Jan Frylinck,3,0,30,0,10.00,3,2,1,1,0
5,United Arab Emirates Vs Namibia,Namibia,Ben Shikongo,1,0,8,1,8.00,1,1,0,0,0
6,United Arab Emirates Vs Namibia,United Arab Emirates,Basil Hameed,3,0,17,2,5.66,10,2,0,0,0

In [ ]:
# For all matches

import pandas as pd
headers = ["match", "bowlingTeam", "bowlerName", "overs", "maiden", "runs", "wickets", "economy", "0s", "4s", "6s", "wides", "noBalls"]
bowling_data = pd.DataFrame(columns = headers)

for link in match_links:
  match_url = link
  match_page = requests.get(match_url)
  soup = BeautifulSoup(match_page.text, 'html.parser')

  if soup.find_all("span", class_="ds-text-title-xs ds-font-bold ds-capitalize"):
    teams = soup.find_all("span", class_="ds-text-title-xs ds-font-bold ds-capitalize")
    team1 = teams[0].text
    team2 = teams[1].text
    match = team1 + ' Vs ' + team2

    tables = soup.find_all("table", class_="ds-w-full ds-table ds-table-md ds-table-auto ")
    team1_bowling = tables[0]
    team2_bowling = tables[1]
  else:
    continue

  # print(team1_bowling)
  # print(team2_bowling)

  for j in team1_bowling.find_all('tr')[1:]:
    if len(j.find_all('td')) == 11:
      row_data = j.find_all('td')
    else:
      continue
    
    full_row = [match, team2]
    rest_row = [i.text for i in row_data]
    full_row.extend(rest_row)

    length = len(bowling_data)
    bowling_data.loc[length] = full_row

  # bowling_data

  for j in team2_bowling.find_all('tr')[1:]:
    if len(j.find_all('td')) == 11:
      row_data = j.find_all('td')
    else:
      continue
    
    full_row = [match, team1]
    rest_row = [i.text for i in row_data]
    full_row.extend(rest_row)

    length = len(bowling_data)
    bowling_data.loc[length] = full_row

  # bowling_data

In [ ]:
bowling_data

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
486,Pakistan Vs England,Pakistan,Naseem Shah,4,0,30,0,7.50,15,3,1,1,0
487,Pakistan Vs England,Pakistan,Haris Rauf,4,0,23,2,5.75,13,3,0,1,0
488,Pakistan Vs England,Pakistan,Shadab Khan,4,0,20,1,5.00,10,1,0,0,0
489,Pakistan Vs England,Pakistan,Mohammad Wasim,4,0,38,1,9.50,5,5,0,2,0
490,Pakistan Vs England,Pakistan,Iftikhar Ahmed,0.5,0,13,0,15.60,0,1,1,0,0

In [ ]:
bowling_data.shape

(491, 13)

In [ ]:
# Export to csv
bowling_data.to_csv('Bowling_summary.csv', index=False)

In [ ]:
# Made some changes/updations to file in excel

In [ ]:
# Map Match Ids so that we can connect Matches table with Batting Summary table
df_match = pd.read_csv('Match_summary.csv')

match_ids_dict = {}
for index, row in df_match.iterrows():
    key1 = row['team1'] + ' Vs ' + row['team2']
    key2 = row['team2'] + ' Vs ' + row['team1']
    match_ids_dict[key1] = row['match_id']
    match_ids_dict[key2] = row['match_id']

In [ ]:
df_bowling = pd.read_csv('Bowling_summary.csv')
df_bowling['match_id'] = df_bowling['match'].map(match_ids_dict)