In [1]:
!pip install beautifulsoup4

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.8/dist-packages (4.6.3)

In [2]:
import requests
# Create an URL object
url = 'https://stats.espncricinfo.com/ci/engine/records/team/match_results.html?id=14450;type=tournament'
# Create object page
page = requests.get(url)
print(page)
# If the output is <Response [200]> that means the server allows us to collect data from their website.

<Response [200]>

In [3]:
from bs4 import BeautifulSoup
# parser-lxml = Change html to Python friendly format
# Obtain page's information
soup = BeautifulSoup(page.text, 'lxml')

In [4]:
matches_table = soup.select("table.engineTable")[0]

In [5]:
headers = []
for i in matches_table.find_all('th'):
  title = i.text
  headers.append(title)
print(headers)

['Team 1', 'Team 2', 'Winner', 'Margin', 'Ground', 'Match Date', 'Scorecard']

In [6]:
import pandas as pd
matches_data = pd.DataFrame(columns = headers)

In [7]:
# Create a for loop to fill mydata
for j in matches_table.find_all('tr')[1:]:
  row_data = j.find_all('td')
  row = [i.text for i in row_data]
  length = len(matches_data)
  matches_data.loc[length] = row
matches_data

,Team 1,Team 2,Winner,Margin,Ground,Match Date,Scorecard
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830
5,Sri Lanka,U.A.E.,Sri Lanka,79 runs,Geelong,"Oct 18, 2022",T20I # 1832
6,Ireland,Scotland,Ireland,6 wickets,Hobart,"Oct 19, 2022",T20I # 1833
7,West Indies,Zimbabwe,West Indies,31 runs,Hobart,"Oct 19, 2022",T20I # 1834
8,Netherlands,Sri Lanka,Sri Lanka,16 runs,Geelong,"Oct 20, 2022",T20I # 1835
9,Namibia,U.A.E.,U.A.E.,7 runs,Geelong,"Oct 20, 2022",T20I # 1836
10,Ireland,West Indies,Ireland,9 wickets,Hobart,"Oct 21, 2022",T20I # 1837
11,Scotland,Zimbabwe,Zimbabwe,5 wickets,Hobart,"Oct 21, 2022",T20I # 1838
12,Australia,New Zealand,New Zealand,89 runs,Sydney,"Oct 22, 2022",T20I # 1839
13,Afghanistan,England,England,5 wickets,Perth,"Oct 22, 2022",T20I # 1840
14,Ireland,Sri Lanka,Sri Lanka,9 wickets,Hobart,"Oct 23, 2022",T20I # 1841
15,India,Pakistan,India,4 wickets,Melbourne,"Oct 23, 2022",T20I # 1842
16,Bangladesh,Netherlands,Bangladesh,9 runs,Hobart,"Oct 24, 2022",T20I # 1843
17,South Africa,Zimbabwe,no result,,Hobart,"Oct 24, 2022",T20I # 1844
18,Australia,Sri Lanka,Australia,7 wickets,Perth,"Oct 25, 2022",T20I # 1845
19,England,Ireland,Ireland,5 runs,Melbourne,"Oct 26, 2022",T20I # 1846
20,Afghanistan,New Zealand,abandoned,,Melbourne,"Oct 26, 2022",T20I # 1846a
21,Bangladesh,South Africa,South Africa,104 runs,Sydney,"Oct 27, 2022",T20I # 1847
22,India,Netherlands,India,56 runs,Sydney,"Oct 27, 2022",T20I # 1848
23,Pakistan,Zimbabwe,Zimbabwe,1 run,Perth,"Oct 27, 2022",T20I # 1849
24,Afghanistan,Ireland,abandoned,,Melbourne,"Oct 28, 2022",T20I # 1849a
25,Australia,England,abandoned,,Melbourne,"Oct 28, 2022",T20I # 1849b
26,New Zealand,Sri Lanka,New Zealand,65 runs,Sydney,"Oct 29, 2022",T20I # 1850
27,Bangladesh,Zimbabwe,Bangladesh,3 runs,Brisbane,"Oct 30, 2022",T20I # 1851
28,Netherlands,Pakistan,Pakistan,6 wickets,Perth,"Oct 30, 2022",T20I # 1852
29,India,South Africa,South Africa,5 wickets,Perth,"Oct 30, 2022",T20I # 1853
30,Australia,Ireland,Australia,42 runs,Brisbane,"Oct 31, 2022",T20I # 1855
31,Afghanistan,Sri Lanka,Sri Lanka,6 wickets,Brisbane,"Nov 1, 2022",T20I # 1856
32,England,New Zealand,England,20 runs,Brisbane,"Nov 1, 2022",T20I # 1858
33,Netherlands,Zimbabwe,Netherlands,5 wickets,Adelaide,"Nov 2, 2022",T20I # 1859
34,Bangladesh,India,India,5 runs,Adelaide,"Nov 2, 2022",T20I # 1860
35,Pakistan,South Africa,Pakistan,33 runs,Sydney,"Nov 3, 2022",T20I # 1861
36,Ireland,New Zealand,New Zealand,35 runs,Adelaide,"Nov 4, 2022",T20I # 1862
37,Australia,Afghanistan,Australia,4 runs,Adelaide,"Nov 4, 2022",T20I # 1864
38,England,Sri Lanka,England,4 wickets,Sydney,"Nov 5, 2022",T20I # 1867
39,Netherlands,South Africa,Netherlands,13 runs,Adelaide,"Nov 6, 2022",T20I # 1871
40,Bangladesh,Pakistan,Pakistan,5 wickets,Adelaide,"Nov 6, 2022",T20I # 1872
41,India,Zimbabwe,India,71 runs,Melbourne,"Nov 6, 2022",T20I # 1873
42,New Zealand,Pakistan,Pakistan,7 wickets,Sydney,"Nov 9, 2022",T20I # 1877
43,England,India,England,10 wickets,Adelaide,"Nov 10, 2022",T20I # 1878
44,England,Pakistan,England,5 wickets,Melbourne,"Nov 13, 2022",T20I # 1879

In [8]:
# Export to csv
matches_data.to_csv('WC_matches_22.csv', index=False)